# Generated by Django 5.1.3 on 2024-12-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outro', 'Outro'), ('nao_informar', 'Prefiro não informar')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrocalendario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='RegistroCalendario',
        ),
    ]
