# Generated by Django 5.1.3 on 2024-12-11 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_pessoa_remove_registrocalendario_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='genero',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='O nome deve conter apenas letras e espaços.', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve estar no formato (XX) XXXXX-XXXX.', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')]),
        ),
    ]
