# Generated by Django 5.1.3 on 2024-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_remove_pessoa_genero_alter_pessoa_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(blank=True, choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('outro', 'Outro'), ('nao_informar', 'Prefiro não informar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
